stages:
- stage: dev
  jobs:
  - job: MyJob
    displayName: My First Job
    continueOnError: true
    steps:
    - script: echo My first job
- stage: QA
  jobs:
  - job: QAJob
    displayName: My First Job
    continueOnError: true
    steps:
    - script: echo My first job
