stages:
- stage: dev
  jobs:
  - job: MyJob
    displayName: Dev Job
    continueOnError: true
    steps:
    - script: echo My first job
- stage: QA
  dependsOn: dev
  jobs:
  - job: QAJob
    displayName: QA Job
    continueOnError: true
    steps:
    - script: echo My first job
