stages:
- stage: dev2
  jobs:
  - job: MyJob
    pool: default
    displayName: Dev Job
    continueOnError: true
    steps:
    - script: echo My first job
  
  - deployment: 'DeployK8sresource'
    environment: sgaent-prod.default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy