# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job:
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: hello world
    displayName: 'dotnet build $(buildConfiguration)'

- deployment:
  pool:
    vmImage: 'Ubuntu-16.04'
  environment: Fabfiber-Prod.devd217
  strategy:
    runOnce:
      deploy:
        steps:
        - script: hello world